[theme]

# Primary color
primaryColor = "#d33682"            # A vibrant magenta/pink

# Background color for main area
backgroundColor = "#002b36"         # A dark teal/blue

# Background for sidebar 
secondaryBackgroundColor = "#586e75" # A medium grayish-blue

# Color for text
textColor = "#fff"                   # White text

[client]
toolbarMode = "minimal"              # Minimal toolbar display
